name: Prepare Flutter Engine Source

on: 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # برای جلوگیری از کشته شدن زودتر از موعد توسط گیت‌هاب
    timeout-minutes: 360 

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Install Depot Tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Fetch Flutter Engine
        run: |
          mkdir engine
          cd engine
          fetch --nohooks flutter
          gclient sync --no-history

      - name: Cleanup Git Folders to Save Space
        run: |
          cd engine
          # پاک کردن تمام پوشه‌های .git که به شدت حجم رو اشغال می‌کنن
          find . -name ".git" -type d -exec rm -rf {} +
          echo "پاکسازی فایل‌های گیت انجام شد!"

      - name: Compress and Split Source Code
        run: |
          cd engine
          # این بار پارت‌ها رو ۱۰۰۰ مگابایتی (۱ گیگ) می‌کنیم
          tar -czf - src/ | split -b 1000M - flutter_engine.tar.gz.part_

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: engine-source-v2
          # به جای v1 گذاشتیم v2 که با قبلی تداخل نکنه
          files: engine/flutter_engine.tar.gz.part_*
